"""credential table

Revision ID: 194a24a6b339
Revises: a55c309f1072
Create Date: 2026-08-10 15:22:01.186718
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "194a24a6b339"
down_revision: Union[str, None] = "a55c309f1072"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credential",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("username", sa.String(length=200), nullable=True),
        sa.Column("secret", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credential", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_credential_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credential_project_id"))

    op.drop_table("credential")
    # ### end Alembic commands ###
