"""issue + issue_comment

Revision ID: 609da2fff72f
Revises: 194a24a6b339
Create Date: 2026-08-10 15:47:26.656085
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "609da2fff72f"
down_revision: Union[str, None] = "194a24a6b339"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("assignee", sa.String(length=120), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("result_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issue", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_issue_project_id"), ["project_id"], unique=False)

    op.create_table(
        "issue_comment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issue_comment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_issue_comment_issue_id"), ["issue_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issue_comment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issue_comment_issue_id"))

    op.drop_table("issue_comment")
    with op.batch_alter_table("issue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issue_project_id"))

    op.drop_table("issue")
    # ### end Alembic commands ###
